### ISSUE TITLE
MachineDeployment fails to scale up in autoscaler e2e test

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api#12298]
### Which jobs are flaking?

There have been two failures recently where a Docker MachineDeployment only scales up to 2 replicas instead of 3 before the timeout is reached.

### Which tests are flaking?

[capi-e2e-latestk8s-main](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-latestk8s-main)

### Since when has it been flaking?

5/26/2025

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-latestk8s-main/1927270770996678656

### Label(s) to be applied

/kind flake

**Comment by cprivitere** [comment]
Here's a k8s-triage search link for finding these: https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=replicas%20should%20match%20expected%20replica&job=.*-cluster-api-.*e2e.*&xjob=.*-provider-.*%7C.*-operator-

**Comment by chrischdi** [comment]
Could be that this is gone, last occurency: 18th of June

**Comment by alimaazamat** [comment]
Still ongoing as of 8/25/25 

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-mink8s-main/1959961945092132864

**Comment by alimaazamat** [comment]
Not sure if the following type of test failures also are related. All are ` /home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/machinedeployment_helpers.go` failures
MachineDeployment fails to scale up to 1 https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-mink8s-main/1959100510715777024
Machine Deployment fails to scale up to 2 https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-main/1959581182668574720

**Comment by sbueringer** [comment]
I think in general this is a new issue. It only started occuring since I fixed the more frequently occuring MP autoscaler test flake

**Comment by arshadd-b** [comment]
I think this issue is still appearing 
but now its failing with machine pool , it is on 1.9 
as I see [here](https://github.com/kubernetes-sigs/cluster-api/issues/12298#issuecomment-3221006061) , it was fixed 
did we fix in  main only ?
```
{Timed out after 300.001s.
Timed out waiting for 3 ready replicas for MachinePool autoscaler-t50r8t/autoscaler-t6b50o-mp-0-4kwpv
Expected
    <int>: 2
to equal
    <int>: 3 failed [FAILED] Timed out after 300.001s.
Timed out waiting for 3 ready replicas for MachinePool autoscaler-t50r8t/autoscaler-t6b50o-mp-0-4kwpv
Expected
    <int>: 2
to equal
    <int>: 3
In [It] at: /home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/machinepool_helpers.go:91 @ 09/24/25 09:54:53.805
}
```
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-mink8s-release-1-9/1970765347577401344

**Comment by sbueringer** [comment]
This fix (https://github.com/kubernetes-sigs/cluster-api/pull/12613) was merged on main and backported to release-1.11

**Comment by sbueringer** [comment]
You can try to backport this to older branches, but I'm not sure if it's worth it if it's not straightforward. It was only a test issue, no prod code fix.

Does the test in general still fail on main? (would be good to cleanly separate different test issues if there are multiple ones)

**Comment by arshadd-b** [comment]
Actually what I see from dashboard it is just first occurrence  on 1.9 and not happening on main 
https://storage.googleapis.com/k8s-triage/index.html?text=Timed%20out%20waiting%20for%203%20ready%20replicas%20for%20MachinePool&job=.*cluster-api.*(test%7Ce2e)-(mink8s-)*main&test=When%20using%20the%20autoscaler%20with%20Cluster%20API&xjob=.*-provider-.*

will see if it is repeating, can promote the fix.

**Comment by sbueringer** [comment]
> Does the test in general still fail on main? (would be good to cleanly separate different test issues if there are multiple ones)

Yup. But I think we have other issues in this test on main: https://storage.googleapis.com/k8s-triage/index.html?job=.*cluster-api.*(test%7Ce2e)-(mink8s-)*main&test=When%20using%20the%20autoscaler%20with%20Cluster%20API&xjob=.*-provider-

**Comment by arshadd-b** [comment]
yeah same test but failing due to some different issue , will have a look to debug further, better will create different issue as well  to track it.

**Comment by fabriziopandini** [comment]
I was looking into https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/12973/pull-cluster-api-e2e-main-gke/1987777213264564224 because I saw the issue happening two times in a row on this RP.

> [FAILED] Timed out after 240.001s.
>   The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/machinedeployment_helpers.go:800 with:
>   MachineDeployment autoscaler-aybaoi/autoscaler-t7za0s-md-0-x67lj replicas should match expected replicas
>   Expected
>       <int32>: 1
>   to equal
>       <int32>: 0
>   In [It] at: /home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/machinedeployment_helpers.go:816 @ 11/10/25 

The issues happens when testing autoscaler support for scale down to zero, and the node that sticks around is autoscaler-t7za0s-md-0-x67lj-gjwd6-p6h57 

By looking at the autoscaler logs, when we scale down to zero, the autoscaler reports

> I1110 07:28:53.345956       1 cluster.go:159] Node autoscaler-t7za0s-md-0-x67lj-gjwd6-p6h57 cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: coredns-66bc5c9577-jqssn
> ...
> I1110 07:28:53.345979       1 planner.go:311] 1 nodes found to be unremovable in simulation, will re-check them at 2025-11-10 07:33:52.142339633 +0000 UTC m=+450.301775676

That means that the autoscaler defers deletion of one node due to core-dns pod; autoscaler will recheck after 5m, which is more than current CAPI timeout 4m; additionally the fact that autoscaler will recheck doesn't imply the autoscaler will change decision at the next try.

Digging a bit into the autoscaler code, looks like the "non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present..." message above comes from 
https://github.com/kubernetes/autoscaler/blob/c7b342e183a5e19cf835ac157cb0f21b4a0972e8/cluster-autoscaler/simulator/drainability/rules/system/rule.go#L53 

By looking at this code my TL;DR is;
- Autoscaler runs with values of  --skip-nodes-with-system-pods = true --blocking-system-pod-distruption-timeout=1h
- Unless we change those values, the autoscaler will keep around the node with the core dns pod for 1h

So I'm leaning toward setting --skip-nodes-with-system-pods=false because for the sake of this test it is ok to create some disruption on core dns + there is a MP pool machine and also the CP machine that can host the replacement pod

@chrischdi  @sbueringer @elmiko  opinions?

**Comment by sbueringer** [comment]
Nice catch. Sounds good to me. I hope it's enough to set this flag. I wonder if we still would run into problems if we have 1 CP and no MP Machines (e.g. like in CAPV)

EDIT: Hm looks like we use min-size 2 both in CAPI and in CAPV. So I think we should be fine

**Comment by fabriziopandini** [comment]
When we test scale to 0 min-size is also changed to 0, but this should not be an issue because core dns uses preferredDuringSchedulingIgnoredDuringExecution + it can run on CP machines

**Comment by sbueringer** [comment]
/reopen

Let's check in 1-2 weeks if the flake is gone

**Comment by sbueringer** [comment]
Not sure if it got better or worse

PR got merged on 10 November 6:52 PM GMT+1

Note: This is including jobs from PRs as the test is only failing on PRs somehow
Note: The failures from the last day or so are not visible yet in triage, but there are a few of them

https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=.*cluster-api.*e2e.*main&test=autoscaler&xjob=.*-provider-.*

**Comment by arshadd-b** [comment]
yep , seeing the dashboard, don't see the failures for main 
https://storage.googleapis.com/k8s-triage/index.html?job=.*cluster-api.*(test%7Ce2e)-(mink8s-)*main&test=When%20using%20the%20autoscaler%20with%20Cluster%20API&xjob=.*-provider-

but when I change the date to see old failures, it is showing those 
https://storage.googleapis.com/k8s-triage/index.html?date=2025-10-27&job=.*cluster-api.*(test%7Ce2e)-(mink8s-)*main&test=When%20using%20the%20autoscaler%20with%20Cluster%20API&xjob=.*-provider-

**Comment by arshadd-b** [comment]
May be will continue monitoring to see any flake related to this.

**Comment by sbueringer** [comment]
I meant that it's failing pretty frequently on PRs in cases where the changes in the PR were absolutely fine.

But let's wait a bit longer for latest data after the change we just merged.

**Comment by sbueringer** [comment]
Do we still have this flake?

**Comment by sbueringer** [comment]
This specific flake seems to be gone

(There are two MP autoscaler failures recently but both are bootstrap exec)

/close
